# Generated by Django 4.2.6 on 2023-10-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contactnumber', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('nameofparent', models.CharField(max_length=50)),
                ('aadhaarno', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('permanentaddress', models.CharField(max_length=40)),
                ('payamount', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'std',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('collegename', models.CharField(max_length=40)),
                ('departmentname', models.CharField(max_length=40)),
                ('subject1', models.CharField(max_length=40)),
                ('subject2', models.CharField(max_length=40)),
                ('subject3', models.CharField(max_length=40)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app18.student')),
            ],
            options={
                'db_table': 'clg',
            },
        ),
    ]
